version: '3'

services:
  redis:
    image: redis:latest
    container_name: virtual-space-redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: virtual-space-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
